### ISSUE TITLE
Add contributing.md guide page

### ISSUE THREAD

**Issue by Kasparsu** [TPT-Loane/TPT-Loane#10]
Võtta kasutusele midagi stiilis  https://embeddedartistry.com/blog/2017/08/04/a-github-pull-request-template-for-your-projects/ Modify to our needs.
Title võiks olla WIP algusega kui on tegevuses. ning see ära kaotada kui on valmis reviewks. ning siis jah nt issue nr. Aga panna panna mingi contributing.md file kus siis on guidelines on pull request format w/ examples. Also maybe some guidelines for setting up and tools and plugins but that can also be outside of this issue.

**Comment by Kasparsu** [comment]
@Orzelius you can re-assign this to someone if you see fit for anybody else to do it.

**Comment by Kahuka** [comment]
@Kasparsu Kas see link seal üleval peabki mitte ära laadima. Sest ma seda avada ei saa.

**Comment by GeorgDV** [comment]
@Kahuka Just a note, that usually issues would be closed via just merging related Pull Request. Seems like this is done, so i'll merge [this](https://github.com/TPT-Loane/TPT-Loane/pull/47).
