### ISSUE TITLE
Bootstrap BE

### ISSUE THREAD

**Issue by Orzelius** [TPT-Loane/TPT-Loane#11]
Create a NestJS (with typescript) starter for the BE. Please research a bit before proceeding. Also note that we will be using graphql exclusively so we don't need the REST part of it. Also we will be using the code-first approach for the db and graphql schema.

**Comment by Kasparsu** [comment]
> bootstrap
> /ˈbuːtstrap/
> 
> 
> COMPUTING
> a technique of loading a program into a computer by means of a few initial instructions which enable the introduction of the rest of the program from an input device.
