### ISSUE TITLE
Create fake db data

### ISSUE THREAD

**Issue by Orzelius** [TPT-Loane/TPT-Loane#117]
Create a new `testing` module with a `testing.service` in it. Import (dependency-inject) all other services there and create a function that creates fake data using [faker](https://www.npmjs.com/package/faker) or something similar.

Add a new env var (in .env.example and your own .env), something like `CREATE_FAKE_DATA`. 

Check in code if that variable is set to `true` and if so, create new fake data.

**Comment by GeorgDV** [comment]
note: closing this because its merged
