### ISSUE TITLE
FE: Add Chakra UI library.

### ISSUE THREAD

**Issue by Kasparsu** [TPT-Loane/TPT-Loane#16]
https://chakra-ui.com/docs/getting-started

To Do:

1. add chakra to fe.
2. bootstrap it.
3. update pages/layouts to use chakra components.

**Comment by GeorgDV** [comment]
@tomimarkus991  I know you love Chakra. :P   Something for you to work on.

**Comment by tomimarkus991** [comment]
@GeorgDV should i make a new branch and then PR?

**Comment by GeorgDV** [comment]
> @GeorgDV should i make a new branch and then PR?
Yes. Changes are always added to like that.

**Comment by Orzelius** [comment]
Done with #19
