### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by lupus117** [TPT-Loane/TPT-Loane#24]
# Need to choose and look into the CI-s
## Current options
TravisCI, github runners, circleCI

**Comment by lupus117** [comment]
@Orzelius Millist funktsionaalsust me otsime CI-st, ja mida täpsemalt plaanime tehasellega?

**Comment by Orzelius** [comment]
@lupus117 We speak English here (Estonian/Eng in discord).

> Millist funktsionaalsust me otsime CI-st, ja mida täpsemalt plaanime tehasellega

* Running tests
* Building docker images
* Running lint and code quality stuff
* Continuous deployment
* Cron jobs to check for vulnerabilities
* qode quality analysis
* etc

Basically everything a full blown project like this needs.

**Comment by lupus117** [comment]
It seems like TravisCI is the best option, both for ease of use and it's free pricing for open source projects

**Comment by Orzelius** [comment]
@OskarSchamardin What do you think?

> both for ease of use

Can you bring any examples compared to the other options?

> free pricing for open source projects

Aren't all three of these free for open-source?

I'd also consider the integration capabilities with github a point that should be looked at.

**Comment by lupus117** [comment]
> Aren't all three of these free for open-source?

github runners are also free for open source projects, but CircleCI's free tier is more limited than the other 2 options

> I'd also consider the integration capabilities with github a point that should be looked at.

TravisCI has superb github integration, as well as some added options and ease of use when compared to github runners

**Comment by Orzelius** [comment]
Then it's decided. Closing this issue with the decision for Travis

cc @TPT-Loane/devops
