### ISSUE TITLE
Create basic layout components

### ISSUE THREAD

**Issue by GeorgDV** [TPT-Loane/TPT-Loane#26]
This issue can be taken apart by each component and be closed after multiple pull requests.

Some components that should be included with Chakra:

- [x]  **Header** (navigation bar) @GeorgDV 

Display a header component that serves as navbar.

Maybe something from here can be used -> https://chakra-templates.dev/navigation/navbar

---
- [x] **Footer** (with some content) @GeorgDV 

Display footer. Perhaps a smaller one with minimal data.

Maybe something from here -> https://chakra-templates.dev/page-sections/footer

---
- [x] **Content** (product cards content go here) @GeorgDV 

Maybe just a Box component?

---
- [x] (with or after Content) **Card** component to display product. @GeorgDV 

In Content area display cards with loanable products.

Perhaps a product card from here -> https://chakra-templates.dev/components/cards

---
- [x] **Sidebar** (in future for admin view only, should be collapsable and disappear on mobile screens) @tomimarkus991 

Maybe something from here? -> https://chakra-ui.com/docs/overlay/drawer
Depends on if we want it to be responsive while we are using other parts of the page.

---
Some reference on how the main page layout might look like:
![reference](https://user-images.githubusercontent.com/48998862/115360288-2ae34280-a1c8-11eb-96ad-72d74c9a38ea.JPG)

**Comment by Orzelius** [comment]
I'd add the requirement that the `left` sidebar should disappear on small screens ad should be openable via a button on the `header`. This can be done now as well.

**Comment by Orzelius** [comment]
When @tomimarkus991 finishes with #27 this can be proceeded with

**Comment by GeorgDV** [comment]
@tomimarkus991 @Kahuka If you want you can freely take some component that hasn't got a name from here and work on that.

**Comment by Orzelius** [comment]
@GeorgDV Super nice and detailed issue 👍

**Comment by Kasparsu** [comment]
I have a small feeling that @GeorgDV does not understand how layout files should work and thinks that layout components header footer etc are layout files. Understandable confusion some what. @GeorgDV please take a look at how nuxt does them. https://nuxtjs.org/docs/2.x/directory-structure/layouts or how laravel does them https://laravel.com/docs/8.x/blade#building-layouts . If you have further questions let me know I will try to illustrate better. I mean work that you are doing is fine but some structure changes will be needed at some point.

**Comment by GeorgDV** [comment]
@Kasparsu Thanks, i'll take a deeper look. 👍

**Comment by tomimarkus991** [comment]
> 
> 
> This issue can be taken apart by each component and be closed after multiple pull requests.
> 
> Some components that should be included with Chakra:
> 
>     * [x]   **Header** (navigation bar) @GeorgDV
> 
> 
> Display a header component that serves as navbar.
> 
> Maybe something from here can be used -> https://chakra-templates.dev/navigation/navbar
> 
>     * [ ]  **Footer** (with some content) @GeorgDV
> 
> 
> Display footer. Perhaps a smaller one with minimal data.
> 
> Maybe something from here -> https://chakra-templates.dev/page-sections/footer
> 
>     * [ ]  **Content** (product cards content go here)
> 
> 
> Maybe just a Box component?
> 
>     * [ ]  (with or after Content) **Card** component to display product.
> 
> 
> In Content area display cards with loanable products.
> 
> Perhaps a product card from here -> https://chakra-templates.dev/components/cards
> 
>     * [ ]  **Sidebar** (in future for admin view only, should be collapsable and disappear on mobile screens)
> 
> 
> Maybe something from here? -> https://chakra-ui.com/docs/overlay/drawer
> Depends on if we want it to be responsive while we are using other parts of the page.
> 
> Some reference on how the main page layout might look like:
> ![reference](https://user-images.githubusercontent.com/48998862/115360288-2ae34280-a1c8-11eb-96ad-72d74c9a38ea.JPG)

**Comment by tomimarkus991** [comment]
missclick

**Comment by tomimarkus991** [comment]
Sidebar (in future for admin view only, should be collapsable and disappear on mobile screens)
what does **in future for admin view only** mean

**Comment by GeorgDV** [comment]
> Sidebar (in future for admin view only, should be collapsable and disappear on mobile screens)
> what does **in future for admin view only** mean

It means that it might be for admin use only later (some admin tools are included), but that's not relevant at the moment.

**Comment by tomimarkus991** [comment]
How do mobile users access the content that is on drawer?

**Comment by GeorgDV** [comment]
> How do mobile users access the content that is on drawer/sidebar?

The sidebar should be mobile-friendly.

**Comment by tomimarkus991** [comment]
Sidebar (in future for admin view only, should be collapsable and **_disappear on mobile screens_**)

**Comment by GeorgDV** [comment]
> do you mean like this?

Something like that yes.
Also, see first comment:

> I'd add the requirement that the left sidebar should disappear on small screens ad should be openable via a button on the header. This can be done now as well.

**Comment by Kasparsu** [comment]
with correct layout implementation you can have 2 page layouts. Default without sidebar and admin with side bar. or vice versa depending on what has more pages.

**Comment by tomimarkus991** [comment]
@GeorgDV will it be a drawer or sidebar? 
Drawer: it can only be used and seen when user clicks hamburger menu to open it.
Sidebar: always visible(when screen is too small it will be replaced with drawer)

**Comment by GeorgDV** [comment]
> @GeorgDV will it be a drawer or sidebar?
> Drawer: it can only be used and seen when user clicks hamburger menu to open it.
> Sidebar: always visible(when screen is too small it will be replaced with drawer)

Depends on how it would be better for the users. But i think it would be a Sidebar, as you described. 🤔 
From @Orzelius 's comment at least i understand it like that as well.

**Comment by tomimarkus991** [comment]
@GeorgDV and it will become drawer for smaller screens?

**Comment by GeorgDV** [comment]
> @GeorgDV and it will become drawer for smaller screens?

Yes, i think so. Does @Orzelius have any conclusive thoughts?

**Comment by GeorgDV** [comment]
@hendrik363 The Content/Card component(s) are open if you want. They should be **Home** page specific components. For now they dont have to look like much and you can use dummy content.

**Comment by Orzelius** [comment]
> Sidebar: always visible(when screen is too small it will be replaced with drawer)

^ This
