### ISSUE TITLE
Create travis FE build

### ISSUE THREAD

**Issue by Orzelius** [TPT-Loane/TPT-Loane#35]
I gave travis access to the github org so it should see this repo as well.

What the build should accomplish:
* Run tests (currently there are none, but it can still fire the `npm run test` command)
* Run lint
* Run build

This build should run on every commit in every branch. Also, please make sure that if any of the steps fail the pr can't be merged and it can be easilly understood what's wrong.

I don't have any experience with Travis, but I'll learn as well. (for now you're on your own)

**Comment by Orzelius** [comment]
@TPT-Loane/devops I think this should take priority over #13

**Comment by OskarSchamardin** [comment]
@lupus117 Can you handle this for the moment? I'm currently handling issue #13.

**Comment by lupus117** [comment]
On it!
