### ISSUE TITLE
Add Routes to FE

### ISSUE THREAD

**Issue by Orzelius** [TPT-Loane/TPT-Loane#4]
### Add first routes to FE

Add three routes:
1. `/` -  home page
2.  `/about` - about page
3. error (not found) route, for when a route is entered that the app doesn't know of (e.g. `/asdasd`)

This should be accomplished using the [react router](https://reactrouter.com/).
With the addition of these pages the structure of the fe project should look like this
```
components/
--Home/
----Home.tsx
----index.ts
--About/
----About.tsx
----index.ts
--Error/
----Error.tsx
----index.ts
index.tsx
App.tsx
```

All the react components in the `/components` folder should be exported and imported through the `index.ts` files
For example the evergreen component library has a similar structure [example](https://github.com/segmentio/evergreen/blob/master/src/buttons/index.js) <- everything is exported from the index file in the component folder.

**Comment by Orzelius** [comment]
@GeorgDV You can complete this yourself or delegate to somebody else.

**Comment by Kasparsu** [comment]
Error should be catching other errors as well 404 is not only error code in existance! Also my suggestion is to use https://http.cat/ in there for some fun, but I leave that decision with @GeorgDV

**Comment by Orzelius** [comment]
I love the error cats idea, it's fun and super educational (importing images through webpack programmatically + future pwa support are both things I've had some trouble with before).

But this is a bit out of the scopes for this issue, maybe I'll create a new one :)

**Comment by Kasparsu** [comment]
> I love the error cats idea, it's fun and super educational (importing images through webpack programmatically + future pwa support are both things I've had some trouble with before).
> 
> But this is a bit out of the scopes for this issue, maybe I'll create a new one :)

why not rollup? I've used webpack, but recently have seen ppl and projects have been more and more using rollup. Maybe worth of exploring or trying out.

**Comment by Orzelius** [comment]
> why not rollup?

Because cra (create-react-app), which I used to bootstrap the React FE part uses webpack under the hood anyways

**Comment by Kasparsu** [comment]
> Because cra (create-react-app), which I used to bootstrap the React FE part uses webpack under the hood anyways

fair enough. didn't look deep enough I guess.

**Comment by GeorgDV** [comment]
Aight, i'll look into it. Cats are always fun.

**Comment by Orzelius** [comment]
Don't do the cats part here, it's a separate topic (quite complicated) and I'll create a new issue about it

**Comment by GeorgDV** [comment]
> Don't do the cats part here, it's a separate topic (quite complicated) and I'll create a new issue about it

Okay

**Comment by Kasparsu** [comment]
maybe separate pages components from regular components like this and add layouts or
```
components/
layouts/
pages/
--Home/
----Home.tsx
----index.ts
--About/
----About.tsx
----index.ts
--Error/
----Error.tsx
----index.ts
index.tsx
App.tsx
```

like this 
```
components/
--layouts/
--pages/
---Home/
-----Home.tsx
-----index.ts
---About/
-----About.tsx
-----index.ts
---Error/
-----Error.tsx
-----index.ts
index.tsx
App.tsx
```
