### ISSUE TITLE
FE: make eslintimport/no-internal-modules rule more usable

### ISSUE THREAD

**Issue by Orzelius** [TPT-Loane/TPT-Loane#58]
The current rule:
```yml
  import/no-internal-modules:
    [
      'error',
      {
        'allow':
          [
            '**/assets/*',
            '**/styles/*',
            '**/components/layouts/*',
            '**/components/custom/*',
            '**/pages/*',
          ],
      },
    ]
```

Proposal:
```yml
  import/no-internal-modules:
    [
      'error',
      {
        'allow':
          [
            '**/assets/*',
            '**/styles/*',
            '**/index.ts',
          ],
      },
    ]
```
---
This will make it so that in the `src` folder imports are only allowed from the index files. I think this is better because new paths won't have to be added.

**Comment by Orzelius** [comment]
@GeorgDV wdyt?

**Comment by GeorgDV** [comment]
> @GeorgDV wdyt?

If it makes it easier for future imports then i like the idea. 👍 
Then again we could have prettier imports once we just have enough path rules set, but i guess that could be more hassle in general than doing this.
