### ISSUE TITLE
Add possibility to switch between "dark" and "light" theme

### ISSUE THREAD

**Issue by GeorgDV** [TPT-Loane/TPT-Loane#69]
A purely cosmetic add-on. Should be simple enough using `chackra-ui`. The possibility to switch theme should go to `Header` component probably.

A new component `ThemeToggler`, etc.

Perhaps something like this could work, check out section **Toggle between the themes** -> [here](https://blog.logrocket.com/how-to-create-forms-with-chakra-ui-in-react-apps/).

Reference: https://blog.logrocket.com/wp-content/uploads/2020/07/valueoflocalstoragechanges.gif

**Comment by GeorgDV** [comment]
@TPT-Loane/front-end This is up for grabs if there if you don't have any work.

**Comment by Kasparsu** [comment]
this should also take into account user(browser) preffered state. And maybe (if you are up for this) use light sensor api to offer user option to switch. if it is dark offer dark scheme if light theme is on and vice versa. https://developer.mozilla.org/en-US/docs/Web/API/AmbientLightSensor, https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by Kasparsu** [comment]
maybe some other good links to look at are chakra ui docs https://chakra-ui.com/docs/hooks/use-media-query https://chakra-ui.com/docs/overlay/alert-dialog https://chakra-ui.com/docs/features/color-mode
