### ISSUE TITLE
Create a contribution tracker

### ISSUE THREAD

**Issue by Orzelius** [TPT-Loane/TPT-Loane#71]
Create a new repository in the TPT-Loane organisation and create a contribution tracker.

Things it should show about each org member:
* Commit number
* PR number
* Comments number
* Code review numbers
* Issue numbers

Things it should do:
* Be accessible from the web
* Should be able to show data nicely
* Should be able to update regularly
* Should be deployed automatically
* Should be possible to select data by a date range
* Should use the github Graphql API

You can choose any stack you want. As long as it works I'm good. I know some people might hate the current stack so I give you free hands.

But note: this is a small project and should be done somewhat fast, don't spend too much time on this.

**Comment by OskarSchamardin** [comment]
Hello world via static site served by expressJS. [Link to repo](https://github.com/TPT-Loane/Contribution-Tracker).

**Comment by OskarSchamardin** [comment]
> Hello world via static site served by expressJS. [Link to repo](https://github.com/TPT-Loane/Contribution-Tracker).

It can make queries to github and display data. Now we need to make it comfortable to use.

**Comment by OskarSchamardin** [comment]
Basic readable (although not very pretty) user interface.
![Selection_001](https://user-images.githubusercontent.com/49496023/117585800-0e7a5c00-b11d-11eb-8c27-f25860462bd3.png)

**Comment by OskarSchamardin** [comment]
Contribution tracker is basically finished.

This can be currently found [at this link](https://tptloanecontributiontracker3-env.eba-zmmir3sx.eu-west-1.elasticbeanstalk.com/).
