### ISSUE TITLE
Create a Product Detail page

### ISSUE THREAD

**Issue by tomimarkus991** [TPT-Loane/TPT-Loane#74]
just a page that has mock data maybe about the product

**Comment by GeorgDV** [comment]
As reference, maybe the page might look like something like this:

![page](https://user-images.githubusercontent.com/48998862/116985322-f6e24400-acd4-11eb-9940-4f0dbee56ff9.jpg)

Perhaps logic like this would be suitable as a starting point: 
**Picture of loanable product on left -> All other data about it on the right (Name -> Description, etc) + Option to loan it**

Should also take into account the sidebar on bigger screens, and mobile responsivness of the page content on small screens.

**Comment by tomimarkus991** [comment]
@GeorgDV can you send me a link to that page please?

**Comment by GeorgDV** [comment]
> @GeorgDV can you send me a link to that page please?

It was just some random googled example, but not from a real shopping page.
https://elements.envato.com/dailyui-v8-laptop-product-detail-page-ui-website-LP9DH8N
