### ISSUE TITLE
Create a | Create Product page

### ISSUE THREAD

**Issue by tomimarkus991** [TPT-Loane/TPT-Loane#77]
Just make a new page, where you can fill out a form and after submitting it should console log the input

I would use [formik ](https://formik.org/docs/overview) for forms.
It's really nice and works very well with our stack

**Comment by hendrik363** [comment]
What values should the product have, besides the name? @tomimarkus991

**Comment by GeorgDV** [comment]
@hendrik363 [Here](https://github.com/TPT-Loane/TPT-Loane/issues/68) you can see different values for different upcoming entities. But i think you can start with using 2 values:
```
name: string
description: string
```

Name should be a normal string [input](https://chakra-ui.com/docs/form/input) element, but description should probably be a [textarea](https://chakra-ui.com/docs/form/textarea) element (meaning it can hold multiple lines of strings).

**Comment by GeorgDV** [comment]
Also make sure to assign yourself to the issue that you've chosen to do.
